export const NIL: any;
export const parse: any;
export const stringify: any;
export const v1: any;
export const v3: any;
export const v4: any;
export const v5: any;
export const validate: any;
export const version: any;
